#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("work_tripp_recorder.Resource", IsApplication=true)]

namespace work_tripp_recorder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040009
			public const int btnCompilationDay = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int btnCompilationPeriod = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int btnListAllReports = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int btnNewReport = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int btnPickDate = 2130968591;
			
			// aapt resource value: 0x7f040022
			public const int btnSaveReport = 2130968610;
			
			// aapt resource value: 0x7f040005
			public const int gridLayout1 = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int itemListView = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int linearLayout1 = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int linearLayout2 = 2130968592;
			
			// aapt resource value: 0x7f040013
			public const int linearLayout3 = 2130968595;
			
			// aapt resource value: 0x7f040016
			public const int linearLayout4 = 2130968598;
			
			// aapt resource value: 0x7f040019
			public const int linearLayout5 = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int linearLayout6 = 2130968604;
			
			// aapt resource value: 0x7f04001f
			public const int linearLayout7 = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int linearLayout8 = 2130968589;
			
			// aapt resource value: 0x7f040018
			public const int txtCompanyPerson = 2130968600;
			
			// aapt resource value: 0x7f040001
			public const int txtDate = 2130968577;
			
			// aapt resource value: 0x7f040012
			public const int txtFromCity = 2130968594;
			
			// aapt resource value: 0x7f040021
			public const int txtMileageEnd = 2130968609;
			
			// aapt resource value: 0x7f04001e
			public const int txtMileageStart = 2130968606;
			
			// aapt resource value: 0x7f040000
			public const int txtName = 2130968576;
			
			// aapt resource value: 0x7f04001b
			public const int txtPurpose = 2130968603;
			
			// aapt resource value: 0x7f040015
			public const int txtToCity = 2130968597;
			
			// aapt resource value: 0x7f040002
			public const int txtTotalMileage = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int txtVisited = 2130968579;
			
			// aapt resource value: 0x7f040017
			public const int txvCompanyPerson = 2130968599;
			
			// aapt resource value: 0x7f04000c
			public const int txvDate = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int txvFromCity = 2130968593;
			
			// aapt resource value: 0x7f040006
			public const int txvMainTitle = 2130968582;
			
			// aapt resource value: 0x7f040020
			public const int txvMileageEnd = 2130968608;
			
			// aapt resource value: 0x7f04001d
			public const int txvMileageStart = 2130968605;
			
			// aapt resource value: 0x7f04001a
			public const int txvPurpose = 2130968602;
			
			// aapt resource value: 0x7f04000e
			public const int txvSelectedDate = 2130968590;
			
			// aapt resource value: 0x7f040014
			public const int txvToCity = 2130968596;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int ItemRowView = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ListReports = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int NewReport = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
