#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("work_tripp_recorder.Resource", IsApplication=true)]

namespace work_tripp_recorder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int car = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int btnCompilationDay = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int btnCompilationPeriod = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int btnDayPickDate = 2131099650;
			
			// aapt resource value: 0x7f060037
			public const int btnDetailEdit = 2131099703;
			
			// aapt resource value: 0x7f06003f
			public const int btnEditSave = 2131099711;
			
			// aapt resource value: 0x7f06000c
			public const int btnListAllReports = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int btnNewReport = 2131099659;
			
			// aapt resource value: 0x7f060013
			public const int btnPickDate = 2131099667;
			
			// aapt resource value: 0x7f060026
			public const int btnSaveReport = 2131099686;
			
			// aapt resource value: 0x7f060009
			public const int gridLayout1 = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int imageView1 = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int itemListView = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout1 = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int linearLayout2 = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout3 = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout4 = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout5 = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int linearLayout6 = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int linearLayout7 = 2131099683;
			
			// aapt resource value: 0x7f060011
			public const int linearLayout8 = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int space2 = 2131099648;
			
			// aapt resource value: 0x7f06001c
			public const int txtCompanyPerson = 2131099676;
			
			// aapt resource value: 0x7f060004
			public const int txtDate = 2131099652;
			
			// aapt resource value: 0x7f060027
			public const int txtDateLabel = 2131099687;
			
			// aapt resource value: 0x7f060001
			public const int txtDayDate = 2131099649;
			
			// aapt resource value: 0x7f060028
			public const int txtDetailDate = 2131099688;
			
			// aapt resource value: 0x7f060036
			public const int txtDetailDistance = 2131099702;
			
			// aapt resource value: 0x7f06002a
			public const int txtDetailFromCity = 2131099690;
			
			// aapt resource value: 0x7f060034
			public const int txtDetailMileageEnd = 2131099700;
			
			// aapt resource value: 0x7f060032
			public const int txtDetailMileageStart = 2131099698;
			
			// aapt resource value: 0x7f060030
			public const int txtDetailPurpose = 2131099696;
			
			// aapt resource value: 0x7f06002c
			public const int txtDetailToCity = 2131099692;
			
			// aapt resource value: 0x7f06002e
			public const int txtDetailVisited = 2131099694;
			
			// aapt resource value: 0x7f060035
			public const int txtDistance = 2131099701;
			
			// aapt resource value: 0x7f060038
			public const int txtEditDate = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int txtEditFromCity = 2131099705;
			
			// aapt resource value: 0x7f06003e
			public const int txtEditMileageEnd = 2131099710;
			
			// aapt resource value: 0x7f06003d
			public const int txtEditMileageStart = 2131099709;
			
			// aapt resource value: 0x7f06003c
			public const int txtEditPurpose = 2131099708;
			
			// aapt resource value: 0x7f06003a
			public const int txtEditToCity = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int txtEditVisited = 2131099707;
			
			// aapt resource value: 0x7f060016
			public const int txtFromCity = 2131099670;
			
			// aapt resource value: 0x7f060029
			public const int txtFromCityLabel = 2131099689;
			
			// aapt resource value: 0x7f060025
			public const int txtMileageEnd = 2131099685;
			
			// aapt resource value: 0x7f060033
			public const int txtMileageEndLabel = 2131099699;
			
			// aapt resource value: 0x7f060022
			public const int txtMileageStart = 2131099682;
			
			// aapt resource value: 0x7f060031
			public const int txtMileageStartLabel = 2131099697;
			
			// aapt resource value: 0x7f060003
			public const int txtName = 2131099651;
			
			// aapt resource value: 0x7f06001f
			public const int txtPurpose = 2131099679;
			
			// aapt resource value: 0x7f06002f
			public const int txtPurposeLabel = 2131099695;
			
			// aapt resource value: 0x7f060019
			public const int txtToCity = 2131099673;
			
			// aapt resource value: 0x7f06002b
			public const int txtToCityLabel = 2131099691;
			
			// aapt resource value: 0x7f060005
			public const int txtTotalMileage = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int txtVisited = 2131099654;
			
			// aapt resource value: 0x7f06002d
			public const int txtVisitedLabel = 2131099693;
			
			// aapt resource value: 0x7f06001b
			public const int txvCompanyPerson = 2131099675;
			
			// aapt resource value: 0x7f060010
			public const int txvDate = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int txvFromCity = 2131099669;
			
			// aapt resource value: 0x7f06000a
			public const int txvMainTitle = 2131099658;
			
			// aapt resource value: 0x7f060024
			public const int txvMileageEnd = 2131099684;
			
			// aapt resource value: 0x7f060021
			public const int txvMileageStart = 2131099681;
			
			// aapt resource value: 0x7f06001e
			public const int txvPurpose = 2131099678;
			
			// aapt resource value: 0x7f060012
			public const int txvSelectedDate = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int txvToCity = 2131099672;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Day = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ItemRowView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ListReports = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int NewReport = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ReportDetails = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ReportEdit = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int car = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
